### ISSUE TITLE
2 similar modules can be added to Selected modules

### ISSUE THREAD

**Issue by tzzzening** [AY1920S2-CS2113-T15-3/tp#41]
When printing out the Module Plan, it shows that the same module can be added to the semester twice. The following is the code fragment output:

Okay! Here is your module plan:
2018/2019 SEM2
1.[✗] ID: CS2113 Name: Software Engineering & Object-Oriented Programming | Sem: 2018/2019 SEM2
2.[✗] ID: IS4241 | Sem: 2018/2019 SEM2
3.[✗] ID: IS4241 Name: Social Media Network Analysis | Sem: 2018/2019 SEM2

Will fix it when I have time, or whoever that has time can fix it

**Comment by RenzoTsai** [comment]
I think we get this problem because IS4241 is not in the `availableModulesList` and we allow users  to add modules which are not in the `availableModulesList` to semester. If we require user must add modules which are in the  `availableModulesList`（e.g cause an exception if they try to add a "illegal" one) this problem will be solved!

**Comment by RenzoTsai** [comment]
I think I have fixed this bug in the new [PR](https://github.com/AY1920S2-CS2113-T15-3/tp/pull/48).
